# Generated by Django 4.2.29 on 2026-03-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dni',
            new_name='rut',
        ),
    ]
